### ISSUE TITLE
example mesos slave playbook?

### ISSUE THREAD

**Issue by skinney6** [AnsibleShipyard/ansible-chronos#8]
Could you add an example playbook for a mesos slave? 
These are great. 
Thanks very much!

**Comment by ernestas-poskus** [comment]
1) Clone: java, zookeeper and mesos repositories into your roles path defined by ansible.cfg 

``` ansible.cfg
roles_path    = /etc/ansible/roles
```

2) Create testing environment e.g.: Vagrant CentOS 7

3) Run playbook

``` yaml
# Java + Zookeeper + Mesos
- name: Java + Zookeeper + Mesos [master-slave]
  hosts: all
  sudo: yes
  roles:
    - role: ansible-java
      java_packages:
        - java-1.8.0-openjdk

    - role: ansible-zookeeper
      zookeeper_version: 3.4.8

    - role: ansible-mesos
      mesos_install_mode: master-slave
      mesos_ip: 127.0.0.1
      mesos_version: '0.28.1'
```

Mesos requires zookeeper for master elections, zookeeper requires Java, so following should be installed.
